name: frostcolor
description: "Using the hex code makes it so the colors can be used in Flutter."
version: 1.0.0
homepage: https://github.com/frostaloncode
repository: https://github.com/frostaloncode/frostcolor
documentation: https://github.com/frostaloncode/frostcolor/wiki
example:
  path: example/

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

